server:
    port: 8080
spring:
    application:
        name: API-GATEWAY-SERVICES
    config:
        import: optional:configserver:http://localhost:8888
    profiles:
        active: prod
    cloud:
     gateway:
      routes:
      - id: LANDLORD-SERVICES
        uri: lb://LANDLORD-SERVICES
        predicates:
          - Path=/property-details/**,/property-types/**,/amenities/**, /disclosures**,/common-lease-clauses**,/common-rules**,/auth/**
        filters:
          - AuthenticationFilter
    
      - id: LOGIN-SERVICES  
      #  uri: http://localhost:8085
        uri: lb://LOGIN-SERVICES
      
        predicates:
          - Path=/auth/**
          
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
       defaultZone: http://localhost:8761/eureka