# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - agentrealwebapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'
  build2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
         repository: Pardhasaradhi54/ServiceRegistry
         ref: main
         token: ${{ secrets.GH_PAT }}

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  build3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
         repository: Pardhasaradhi54/LoginService
         ref: main
         token: ${{ secrets.GH_PAT }}

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar' 

  build4:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
         repository: Pardhasaradhi54/LandlordServices
         ref: main
         token: ${{ secrets.GH_PAT }}

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'             
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build1,build2]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app
      
      - name: ApiGateWay Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'agentrealwebapp'
          slot-name: 'agentrealwebapp-apigateway'
          package: '*ApiGateWay*.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_26D6F30EEB204133BF72677F52DDF999 }}

      - name: ServiceRegistry Deploy to Azure Web App
        id: deploy-to-webapp2
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'agentrealwebapp'
          slot-name: 'Production'
          package: '*ServiceRegistry*.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_26D6F30EEB204133BF72677F52DDF999 }}   
